/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BolosRouteImport } from './routes/bolos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CoberturasRouteImport } from './routes/coberturas'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as IngredientesRouteImport } from './routes/ingredientes'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolosRoute = BolosRouteImport.update({
  id: '/bolos',
  path: '/bolos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoberturasRoute = CoberturasRouteImport.update({
  id: '/coberturas',
  path: '/coberturas',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientesRoute = IngredientesRouteImport.update({
  id: '/ingredientes',
  path: '/ingredientes',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bolos': typeof BolosRoute
  '/clientes': typeof ClientesRoute
  '/coberturas': typeof CoberturasRoute
  '/cursos': typeof CursosRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/ingredientes': typeof IngredientesRoute
  '/mcp': typeof McpRoute
  '/pedidos': typeof PedidosRoute
  '/relatorio': typeof RelatorioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolos': typeof BolosRoute
  '/clientes': typeof ClientesRoute
  '/coberturas': typeof CoberturasRoute
  '/cursos': typeof CursosRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/ingredientes': typeof IngredientesRoute
  '/mcp': typeof McpRoute
  '/pedidos': typeof PedidosRoute
  '/relatorio': typeof RelatorioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bolos': typeof BolosRoute
  '/clientes': typeof ClientesRoute
  '/coberturas': typeof CoberturasRoute
  '/cursos': typeof CursosRoute
  '/despesas': typeof DespesasRoute
  '/estoque': typeof EstoqueRoute
  '/ingredientes': typeof IngredientesRoute
  '/mcp': typeof McpRoute
  '/pedidos': typeof PedidosRoute
  '/relatorio': typeof RelatorioRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bolos'
    | '/clientes'
    | '/coberturas'
    | '/cursos'
    | '/despesas'
    | '/estoque'
    | '/ingredientes'
    | '/mcp'
    | '/pedidos'
    | '/relatorio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bolos'
    | '/clientes'
    | '/coberturas'
    | '/cursos'
    | '/despesas'
    | '/estoque'
    | '/ingredientes'
    | '/mcp'
    | '/pedidos'
    | '/relatorio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/bolos'
    | '/clientes'
    | '/coberturas'
    | '/cursos'
    | '/despesas'
    | '/estoque'
    | '/ingredientes'
    | '/mcp'
    | '/pedidos'
    | '/relatorio'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BolosRoute: typeof BolosRoute
  ClientesRoute: typeof ClientesRoute
  CoberturasRoute: typeof CoberturasRoute
  CursosRoute: typeof CursosRoute
  DespesasRoute: typeof DespesasRoute
  EstoqueRoute: typeof EstoqueRoute
  IngredientesRoute: typeof IngredientesRoute
  McpRoute: typeof McpRoute
  PedidosRoute: typeof PedidosRoute
  RelatorioRoute: typeof RelatorioRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolos': {
      id: '/bolos'
      path: '/bolos'
      fullPath: '/bolos'
      preLoaderRoute: typeof BolosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coberturas': {
      id: '/coberturas'
      path: '/coberturas'
      fullPath: '/coberturas'
      preLoaderRoute: typeof CoberturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredientes': {
      id: '/ingredientes'
      path: '/ingredientes'
      fullPath: '/ingredientes'
      preLoaderRoute: typeof IngredientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BolosRoute: BolosRoute,
  ClientesRoute: ClientesRoute,
  CoberturasRoute: CoberturasRoute,
  CursosRoute: CursosRoute,
  DespesasRoute: DespesasRoute,
  EstoqueRoute: EstoqueRoute,
  IngredientesRoute: IngredientesRoute,
  McpRoute: McpRoute,
  PedidosRoute: PedidosRoute,
  RelatorioRoute: RelatorioRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
